# Generated by Django 4.2.2 on 2023-07-08 10:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airvehicles',
            name='brand',
            field=models.CharField(max_length=40, verbose_name='Marka'),
        ),
        migrations.AlterField(
            model_name='airvehicles',
            name='category',
            field=models.ManyToManyField(blank=True, to='product.category', verbose_name='Kategori'),
        ),
        migrations.AlterField(
            model_name='airvehicles',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='airvehicles',
            name='image',
            field=models.ImageField(upload_to='iha', verbose_name='Resim Upload'),
        ),
        migrations.AlterField(
            model_name='airvehicles',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Durum'),
        ),
        migrations.AlterField(
            model_name='airvehicles',
            name='model',
            field=models.CharField(max_length=40, verbose_name='Model'),
        ),
        migrations.AlterField(
            model_name='airvehicles',
            name='slug',
            field=models.SlugField(blank=True, editable=False, null=True, unique=True, verbose_name='Link'),
        ),
        migrations.AlterField(
            model_name='airvehicles',
            name='weight',
            field=models.IntegerField(verbose_name='Ağırlık'),
        ),
    ]
