# Generated by Django 4.2.2 on 2023-07-08 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_airvehicles_brand_alter_airvehicles_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airvehicles',
            name='slug',
            field=models.SlugField(editable=False, max_length=130, unique=True),
        ),
    ]
