# Generated by Django 4.2.2 on 2023-07-08 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_airvehicles_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airvehicles',
            name='slug',
            field=models.SlugField(blank=True, editable=False, unique=True),
        ),
    ]
