# Generated by Django 4.2.2 on 2023-07-08 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_alter_airvehicles_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airvehicles',
            name='image',
            field=models.ImageField(default=1, upload_to='iha', verbose_name='Resim Upload'),
            preserve_default=False,
        ),
    ]
