# Generated by Django 4.2.2 on 2023-07-09 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_airvehicles_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='airvehicles',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Durum (Aktif/Pasif)'),
        ),
    ]
